use crate::span::Span;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum TokenKind {
    Fn,
    Update,
    Query,
    State,
    Event,
    Enum,
    Record,
    Let,
    Match,
    Return,
    If,
    True,
    False,
    Ident(String),
    Int(i64),
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    LAngle,
    RAngle,
    Comma,
    Colon,
    Eq,
    FatArrow,
    Pipe,
    Underscore,
    Arrow,
    Plus,
    Minus,
    Star,
    Slash,
    Semi,
    Eof,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum TokenTag {
    Fn,
    Update,
    Query,
    State,
    Event,
    Enum,
    Record,
    Let,
    Match,
    Return,
    If,
    True,
    False,
    Ident,
    Int,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    LAngle,
    RAngle,
    Comma,
    Colon,
    Eq,
    FatArrow,
    Pipe,
    Underscore,
    Arrow,
    Plus,
    Minus,
    Star,
    Slash,
    Semi,
    Eof,
}

impl From<&TokenKind> for TokenTag {
    fn from(value: &TokenKind) -> Self {
        match value {
            TokenKind::Fn => TokenTag::Fn,
            TokenKind::Update => TokenTag::Update,
            TokenKind::Query => TokenTag::Query,
            TokenKind::State => TokenTag::State,
            TokenKind::Event => TokenTag::Event,
            TokenKind::Enum => TokenTag::Enum,
            TokenKind::Record => TokenTag::Record,
            TokenKind::Let => TokenTag::Let,
            TokenKind::Match => TokenTag::Match,
            TokenKind::Return => TokenTag::Return,
            TokenKind::If => TokenTag::If,
            TokenKind::True => TokenTag::True,
            TokenKind::False => TokenTag::False,
            TokenKind::Ident(_) => TokenTag::Ident,
            TokenKind::Int(_) => TokenTag::Int,
            TokenKind::LParen => TokenTag::LParen,
            TokenKind::RParen => TokenTag::RParen,
            TokenKind::LBrace => TokenTag::LBrace,
            TokenKind::RBrace => TokenTag::RBrace,
            TokenKind::LBracket => TokenTag::LBracket,
            TokenKind::RBracket => TokenTag::RBracket,
            TokenKind::LAngle => TokenTag::LAngle,
            TokenKind::RAngle => TokenTag::RAngle,
            TokenKind::Comma => TokenTag::Comma,
            TokenKind::Colon => TokenTag::Colon,
            TokenKind::Eq => TokenTag::Eq,
            TokenKind::FatArrow => TokenTag::FatArrow,
            TokenKind::Pipe => TokenTag::Pipe,
            TokenKind::Underscore => TokenTag::Underscore,
            TokenKind::Arrow => TokenTag::Arrow,
            TokenKind::Plus => TokenTag::Plus,
            TokenKind::Minus => TokenTag::Minus,
            TokenKind::Star => TokenTag::Star,
            TokenKind::Slash => TokenTag::Slash,
            TokenKind::Semi => TokenTag::Semi,
            TokenKind::Eof => TokenTag::Eof,
        }
    }
}

pub(crate) fn display_tag(tag: &TokenTag) -> &'static str {
    match tag {
        TokenTag::Fn => "`fn`",
        TokenTag::Update => "`update`",
        TokenTag::Query => "`query`",
        TokenTag::State => "`state`",
        TokenTag::Event => "`event`",
        TokenTag::Enum => "`enum`",
        TokenTag::Record => "`record`",
        TokenTag::Let => "`let`",
        TokenTag::Match => "`match`",
        TokenTag::Return => "`return`",
        TokenTag::If => "`if`",
        TokenTag::True => "`true`",
        TokenTag::False => "`false`",
        TokenTag::Ident => "identifier",
        TokenTag::Int => "integer literal",
        TokenTag::LParen => "`(`",
        TokenTag::RParen => "`)`",
        TokenTag::LBrace => "`{`",
        TokenTag::RBrace => "`}`",
        TokenTag::LBracket => "`[`",
        TokenTag::RBracket => "`]`",
        TokenTag::LAngle => "`<`",
        TokenTag::RAngle => "`>`",
        TokenTag::Comma => "`,`",
        TokenTag::Colon => "`:`",
        TokenTag::Eq => "`=`",
        TokenTag::FatArrow => "`=>`",
        TokenTag::Pipe => "`|`",
        TokenTag::Underscore => "`_`",
        TokenTag::Arrow => "`->`",
        TokenTag::Plus => "`+`",
        TokenTag::Minus => "`-`",
        TokenTag::Star => "`*`",
        TokenTag::Slash => "`/`",
        TokenTag::Semi => "`;`",
        TokenTag::Eof => "end of input",
    }
}
