[package]
name    = "counter_app"
version = "0.1.0"
edition = "2021"

[dependencies]
libui = "0.4.0"

# Reference cino crates in the workspace via path dependencies
cino-syntax  = { path = "../../crates/cino-syntax" }
cino-ir      = { path = "../../crates/cino-ir" }
cino-vm      = { path = "../../crates/cino-vm" }
cino-runtime = { path = "../../crates/cino-runtime" }
